using Autodesk.Revit.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DS.RevitLib.Utils.MEP.SystemTree.Relatives
{
    //internal class TeeRelation : ElementRelation
    //{
    //    public TeeRelation(Element element, Element ownNode, XYZ ownDirection) : base(element, ownNode, ownDirection)
    //    {
    //    }

        //public override Relation Get()
        //{
        //    var conDirs = ElementUtils.GetDirections(connectedElement);

        //    if (conDirs.Count != 1)
        //    {
        //        var collinears = conDirs.Where(x => XYZUtils.Collinearity(x, _direction)).ToList();
        //        if (collinears.Any())
        //        {
        //            stack.Push(connectedElement);
        //        }
        //        else
        //        {
        //            _nodeElements.Add(connectedElement);
        //        }
        //    }
        //}
    //}
}
